### ISSUE TITLE
Wabbajack CDN downloads not working

### ISSUE THREAD

**Issue by lukedewolf** [ForgottenGlory/Living-Skyrim-3#218]
LS3 Grass Cache.7z and LS3 SSELODGen Output 3.0.0.7z are not downloading from the Wabbajack CDN. 

Here is the bottom of the log. Whole log attached. 

940,15 - Trying CDN...
940,85 - Trying to find solution to broken download for LS3 SSELODGen Output 3.0.0.7z
940,86 - Looking for generic upgrade for Qz5nRCOoSkY= (5065045600356482627)
941,25 - Looking for generic upgrade for Qz5nRCOoSkY= (5065045600356482627)
941,44 - No solution for broken download LS3 SSELODGen Output 3.0.0.7z WabbajackCDNDownloader+State|https://wabbajack.b-cdn.net/LS3 SSELODGen Output 3.0.0.7z_9176686f-aa2f-4aaf-8988-0f8369cf69ba could be found
941,63 - Hashing Remaining Archives
941,63 - Looking for files to hash
946,47 - Found 15435 total files, 1205 matching filesize
972,8 - Unable to download LS3 Grass Cache.7z (WabbajackCDNDownloader+State|https://wabbajack.b-cdn.net/LS3 Grass Cache.7z_d9055e41-1a15-40d7-b0d0-97896c9dd153)
972,8 - Unable to download LS3 SSELODGen Output 3.0.0.7z (WabbajackCDNDownloader+State|https://wabbajack.b-cdn.net/LS3 SSELODGen Output 3.0.0.7z_9176686f-aa2f-4aaf-8988-0f8369cf69ba)
972,8 - Cannot continue, was unable to download one or more archives
972,8 - File hash check (-42) 7907581ab4ae06d29acc93efb69053cc7a19c532fb2e1a33abc45f267cc0aa31
972,8 - Vacuuming databases
972,8 - Vacuuming completed
972,81 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 68
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 153
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 180
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 174
   at Wabbajack.InstallerVM.<>c__DisplayClass82_0.<<-ctor>b__74>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 369
973,03 - File hash check (-42) 7907581ab4ae06d29acc93efb69053cc7a19c532fb2e1a33abc45f267cc0aa31
[Wabbajack.current.log](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6096050/Wabbajack.current.log)

**Comment by TwistedModding** [comment]
downloading the files from the mirror in the readme or try a vpn
