### ISSUE TITLE
Problem with downloading LivingSkyrim3-modpackage

### ISSUE THREAD

**Issue by Eblis99** [ForgottenGlory/Living-Skyrim-3#426]
Hello,

I want to start by saying, THANK YOU very much! for your amazing work with the livingskyrim3 mod-package! Fantastic job!

Problem with downloading LivingSkyrim3, when I try to download, I get the following error message, read below:

-- Begins --
29,23 - Encountered error, can't continue - System.Exception: File HTTPDownloader+State|https://storage.vectorplexus.com/downloads/monthly_2020_09/High_Poly_Head_v1.4_(SE)_zip.85a520545cc9364ec7561e4bcfed8e75 failed validation
   at Wabbajack.Lib.AInstaller.DownloadArchives() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 225
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 144
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---

I hope you can help fix this problem, and Thank you very much in advance! 

Regards,
/S

**Comment by Eblis99** [comment]
Hi,

I just tried downloading 'LivingSkyrim3' again, and i got the same error message. Se the attached file.


![LivingSkyrim3-Error](https://user-images.githubusercontent.com/87770378/127030068-9dd72b57-5238-4d17-9059-f082dab0a8b8.JPG)

regards,
S

**Comment by ForgottenGlory** [comment]
Solution on Discord.

**Comment by Eblis99** [comment]
Okej, could you please help me by send me the link (the 'solution' for my problem)? I am very very new at this. 

Thank you in advance!
/S
