### ISSUE TITLE
Unable to download More Realistic Gifts for Children.

### ISSUE THREAD

**Issue by Dudditzz** [ForgottenGlory/Living-Skyrim-3#443]
The mod appears to have been removed from Nexus, I am new to Wabbajack modding so forgive me if this is something that is not an issue that can be resolved without the mod being readded to the nexus itself.

2775.07 - Nexus call failed `https://api.nexusmods.com/v1/games/skyrimspecialedition/mods/26977/files/101323/download_link.json`: Wabbajack.Common.Exceptions.HttpException: Http Error Forbidden - Forbidden
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 131
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 131
   at Wabbajack.Lib.Http.Client.GetAsync(String url, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 24
   at Wabbajack.Lib.NexusApi.NexusApiClient.Get[T](String url, Client client) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\NexusApi\NexusApi.cs:line 292
2775.28 - Trying to find solution to broken download for More Realistic Gifts For Children esl-26977-1-0-1564588768.7z
2775.97 - Looking for generic upgrade for 4T50SED6niY= (2782936773761973985)
2776.18 - No solution for broken download More Realistic Gifts For Children esl-26977-1-0-1564588768.7z NexusDownloader+State|SkyrimSpecialEdition|26977|101323 could be found
2776.37 - Hashing Remaining Archives
2776.37 - Looking for files to hash
2776.43 - Found 963 total files, 966 matching filesize
2776.58 - Unable to download More Realistic Gifts For Children esl-26977-1-0-1564588768.7z (NexusDownloader+State|SkyrimSpecialEdition|26977|101323)
2776.58 - Cannot continue, was unable to download one or more archives

**Comment by ForgottenGlory** [comment]
K
