### ISSUE TITLE
Installion Failed

### ISSUE THREAD

**Issue by Treyplex** [ForgottenGlory/Living-Skyrim-3#522]
Hey i have a Problem the download just stopped and it say Installion Failed  and i cant figure out how to solve the problem

Here are my Logs  

40,16 - No solution for broken download Skyrim_Default.ini GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim_default.ini could be found
40,2 - Hashing Remaining Archives
40,2 - Looking for files to hash
40,49 - Found 4091 total files, 968 matching filesize
40,6 - Unable to download Skyrim_Default.ini (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim_default.ini)
40,6 - Cannot continue, was unable to download one or more archives
40,6 - File hash check (-42) 13151f364007d830b1d289c9c9175fee4027c2ddcade94d1d99c78f84214cae8
40,6 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
40,79 - File hash check (-42) 13151f364007d830b1d289c9c9175fee4027c2ddcade94d1d99c78f84214cae8

**Comment by ChunkeeMunkee** [comment]
This is not a modlist bug - please come through to the Discord server if you need general support (as I advised in the DM!)
